### ISSUE TITLE
Nutzung unter Contao 4.13 und PHP 8.1 geplant?

### ISSUE THREAD

**Issue by planepix** [fritzmg/contao-backend-documentation#2]
Hallo Fritz,
ich habe eben die Erweiterung unter Contao 4.13.16 und PHP 8.1 installiert.

Die Installation klappt; aber im Backend ist der Menüpunkt „Dokumentation” nicht so sehen.

Liegt das an der Kombination Contao 4.13 und PHP 8.1?

Ist geplant die Erweiterung auch für 4.13 ff 5.x aktiv weiter zu entwickeln?

Danke und Gruß
Thomas

**Comment by fritzmg** [comment]
Ich habe unter Contao 4.13 kein Problem feststellen können.

Versuche aber trotzdem mal `dev-main`. Das ist außerdem für Contao 5 freigeschalten.

**Comment by planepix** [comment]
Danke dir für den Hinweis auf die dev-main. dev-master ging dann.

Habe ich installiert; aber im Backend kein Eintrag. In den Templates kann ich auch keines auswählen.
Im Vendor-Ordner ist das Modul enthalten…

Dann wird vermutlich eine andere Erweiterung hier die Anzeige verhindern…

Die composer.json aus dieser Installation:
```
{
    "require": {
        "bugbuster/contao-banner-bundle": "^1.3",
        "bugbuster/contao-cron-bundle": "^1.3",
        "bugbuster/contao-dlstats-bundle": "^1.0",
        "bugbuster/contao-visitors-bundle": "^1.6",
        "christianbarkowsky/contao-protectedselect": "^1.1",
        "christianbarkowsky/contao-tiny-compress-images": "^1.0",
        "christianbarkowsky/rel-canonical": "^3.3",
        "codefog/contao-mobile_menu": "^2.6",
        "codefog/contao-news_categories": "^3.4",
        "codefog/contao-social_images": "^3.7",
        "contao/calendar-bundle": "4.13.*",
        "contao/comments-bundle": "4.13.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.13.*",
        "contao/listing-bundle": "4.13.*",
        "contao/manager-bundle": "4.13.*",
        "contao/news-bundle": "4.13.*",
        "contao/newsletter-bundle": "4.13.*",
        "do-while/contao-backupdb-bundle": "^1.2",
        "e-spin/page-info-bundle": "^1.0",
        "erdmannfreunde/contao-grid-bundle": "^1.0",
        "erdmannfreunde/euf_overlay": "^1.2",
        "fritzmg/contao-backend-documentation": "dev-master",
        "fritzmg/contao-sharebuttons": "^2.1",
        "fritzmg/contao-swiper": "^3.3",
        "heimseiten/contao-dark-mode-backend-bundle": "^1.0",
        "heimseiten/contao-sticky-footer-backend-bundle": "^1.0",
        "heimseiten/contao-timeline-bundle": "^1.0",
        "inspiredminds/contao-file-usage": "^1.1",
        "madeyourday/contao-rocksolid-slider": "^2.0",
        "netzmacht/contao-font-awesome-inserttag": "^2.0",
        "omosde/contao-om-backend": "^1.6",
        "omosde/contao-om-search": "^1.0",
        "oveleon/contao-cookiebar": "^1.7",
        "presprog/contao-undo": "^1.0",
        "terminal42/contao-changelanguage": "^3.1",
        "terminal42/contao-conditionalselectmenu": "^3.0",
        "terminal42/contao-easy_themes": "^2.2",
        "terminal42/contao-leads": "^1.4",
        "terminal42/contao-node": "^1.0",
        "terminal42/contao-url-rewrite": "^1.6",
        "terminal42/notification_center": "^1.4",
        "trilobit-gmbh/contao-tiles-bundle": "^1.0",
        "wangaz/contao-jquery-ui-tabs": "^1.1"
    },
    "conflict": {
        "lexik/maintenance-bundle": "2.1.4",
        "symfony/symfony": "3.4.8|4.0.8",
        "doctrine/dbal": "2.9.1|2.9.2",
        "terminal42/contao-changelanguage": "3.3.7 || 3.4.0 || 3.4.1"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}

```

**Comment by fritzmg** [comment]
Diese `composer.json` ist unvollständig:

> Root package is not of type "project", we will not installing Contao extensions.

Dadurch werden bei dir keine Contao 3 extensions installiert. Du musst mindestens

```json
"type": "project"
```

hinzufügen. Danach erst werden folgende Pakete korrekt installiert:

* `fritzmg/contao-backend-documentation`
* `fritzmg/contao-sharebutton`
* `christianbarkowsky/contao-tiny-compress-images`
* `christianbarkowsky/rel-canonical`
* `codefog/contao-mobile_menu`
* `codefog/contao-haste`
* `codefog/contao-social_images`
* `erdmannfreunde/euf_overlay`
* `fritzmg/contao-backend-documentation`
* `fritzmg/contao-sharebuttons`
* `terminal42/contao-conditionalselectmenu`
* `terminal42/contao-easy_themes`
* `terminal42/contao-leads`
* `terminal42/dcawizard`
* `terminal42/notification_center`
* `wangaz/contao-jquery-ui-tabs `

**Comment by planepix** [comment]
Danke dir. Wird nun angezeigt. Das war ein Update aus einer 4.9.
Ist notiert darauf zu achten.
